name: Documentation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ["*"]

concurrency:
  # cancels when a PR gets updated
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  docs:
    name: Build
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: "1"
      - uses: julia-actions/cache@v3
      - name: Setup data directories
        run: |
          wget "https://www.star.bristol.ac.uk/fergus/spectral-fitting/ci-data/1E-1048-5937.tar"
          mkdir ex-datadir
          tar -xf 1E-1048-5937.tar -C ex-datadir/
      - name: Add AstroRegistry and General registries
        shell: julia --color=yes {0}
        run: |
          import Pkg
          Pkg.Registry.add(url="https://github.com/astro-group-bristol/AstroRegistry/")
          Pkg.Registry.add(name="General")
      - name: Set up environment
        shell: julia --color=yes --project=docs {0}
        run: import Pkg; Pkg.instantiate()
        env:
          JULIA_PKG_PRECOMPILE_AUTO: false
      - name: Precompile environment
        shell: julia --color=yes --project=docs {0}
        run: import Pkg; Pkg.precompile()
      - name: Populate SpectralFitting.jl model data
        shell: julia --color=yes --project=docs {0}
        run: import SpectralFitting; SpectralFitting.download_all_model_data()
      - name: Build and deploy documentation
        uses: julia-actions/julia-docdeploy@v1
        env:
          JULIA_NUM_THREADS: "auto"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
